#!/usr/bin/env python3

from random import shuffle
from typing import List


def santas(children: List[str]):
    shuffled_children = children.copy()
    shuffle(shuffled_children)
    assignments = {child: shuffled_children[(i + 1) % len(shuffled_children)]
                   for i, child in enumerate(shuffled_children)}
    return [assignments[child] for child in children]


def main(names):
    for santa in santas([n.strip() for n in names]):
        print(santa)


if __name__ == '__main__':
    import fileinput
    main(fileinput.input())
