#!/usr/bin/env python3

from random import shuffle
from typing import List


def santas(children: List[str]):
    shuffled_children = shuffle(children.copy())
    assignments = {child: shuffled_children[i]
                   for i, child in enumerate(shuffled_children)}
    return [assignments[child] for child in children]


def main(names):
    for santa in santas([n.trim() for n in names]):
        print(santa)


if __name__ == '__main__':
    import fileinput
    main(fileinput.fileinput())
