#!/usr/bin/env python3

from random import shuffle
from typing import List, Dict


def assignments(children: List[str]) -> Dict[str, str]:
    """Returns a dictionary of names mapping child → santa."""
    shuffled_children = children.copy()
    shuffle(shuffled_children)
    return{child: shuffled_children[(i + 1) % len(shuffled_children)]
           for i, child in enumerate(shuffled_children)}


def santas(children: List[str]) -> List[str]:
    """Returns a list of santas that is in the same order as the given
    children."""
    child_to_santa = assignments(children)
    return [child_to_santa[child] for child in children]


def main(names):
    for santa in santas([n.strip() for n in names]):
        print(santa)


if __name__ == '__main__':
    import fileinput
    main(fileinput.input())
